// Phase 4 — shared topic → draft generation pipeline.
//
// One implementation used by BOTH the manual route (POST
// /admin/blog/topics/:id/generate) and the autonomous poller, so a draft
// generated by a human click and one generated by the pipeline are produced
// identically: outline → draft (sanitized HTML) → metadata, reusing the
// Phase-3 blogAi prompt builders + the app's OpenAI client. Always creates a
// blog_posts DRAFT (status='draft') linked to the topic — it NEVER publishes.
//
// The autonomous quality gate (runQualityGate) is applied by the CALLER after
// generation, not here, so the route can surface the draft regardless while the
// poller can leave a failing draft flagged-for-review.

import OpenAI from "openai";
import { db, blogPostsTable, blogTopicsTable, blogProgramSettingsTable } from "@workspace/db";
import { eq } from "drizzle-orm";
import { sanitizeRawBlogHtml } from "./blogHtml";
import {
  buildOutlineMessages,
  buildDraftMessages,
  buildMetadataMessages,
  parseOutline,
  outlineToText,
  cleanDraftHtml,
  clampMetadata,
  parseJsonObject,
  completionText,
  METADATA_FIELDS,
  type DraftBrief,
  type BlogMetadata,
} from "./blogAi";
import {
  slugifyTitle,
  uniqueSlug,
  readingTimeMin,
  normalizeTags,
} from "./blog";

// Match the model used by the Phase-3 blog-ai routes (gpt-4o, non-reasoning).
const MODEL = "gpt-4o";

export interface TopicRow {
  id: number;
  title: string;
  angle: string;
  targetKeyword: string;
}

export interface GeneratedDraft {
  postId: number;
  slug: string;
  title: string;
  bodyHtml: string;
  metadata: Partial<BlogMetadata>;
}

/**
 * Read the operator's editable writing instructions off the singleton program
 * settings row. Returns the raw stored value (may be empty — the prompt builders
 * fall back to the seeded default). Fail-soft: any read error yields null so
 * generation still proceeds against the default brief.
 */
export async function loadWritingInstructions(): Promise<string | null> {
  try {
    const [row] = await db
      .select({ writingInstructions: blogProgramSettingsTable.writingInstructions })
      .from(blogProgramSettingsTable)
      .where(eq(blogProgramSettingsTable.id, 1))
      .limit(1);
    return row?.writingInstructions ?? null;
  } catch {
    return null;
  }
}

/** Build the OpenAI client from the same env the Phase-3 routes use. */
export function getOpenAIClientForProgram(): OpenAI {
  const baseURL = process.env["AI_INTEGRATIONS_OPENAI_BASE_URL"];
  const apiKey = process.env["AI_INTEGRATIONS_OPENAI_API_KEY"];
  if (baseURL && apiKey) return new OpenAI({ baseURL, apiKey });
  const direct = process.env["OPENAI_API_KEY"];
  if (direct) return new OpenAI({ apiKey: direct });
  throw new Error("AI integration not configured.");
}

/**
 * Run a topic through outline → draft → metadata and INSERT a blog_posts DRAFT
 * linked to the topic. Returns the generated draft. Caller is responsible for
 * the topic status transitions (drafting/drafted) + the quality gate; this
 * function only does generation + persistence of the draft row.
 *
 * `existingSlugs` is passed in (the caller already needs the post list) so the
 * generated slug is de-duped without a second query.
 */
export async function generateDraftForTopic(args: {
  openai: Pick<OpenAI, "chat">;
  topic: TopicRow;
  existingSlugs: string[];
  /** Optional concurrency wrapper (the route uses withOpenAIConcurrency). */
  withConcurrency?: <T>(fn: () => Promise<T>) => Promise<T>;
  /** Editable editorial brief (program settings); falls back to the seeded default. */
  writingInstructions?: string | null;
}): Promise<GeneratedDraft> {
  const run = args.withConcurrency ?? ((fn) => fn());
  const writingInstructions = args.writingInstructions;
  const brief: DraftBrief = {
    topic: args.topic.title,
    targetKeyword: args.topic.targetKeyword || undefined,
    notes: args.topic.angle || undefined,
  };

  // 1) Outline.
  const outlineCompletion = await run(() =>
    args.openai.chat.completions.create({
      model: MODEL,
      max_completion_tokens: 900,
      messages: buildOutlineMessages(brief, { writingInstructions }),
    }),
  );
  const outline = parseOutline(completionText(outlineCompletion));
  if (!outline.title) outline.title = args.topic.title;

  // 2) Full draft body (sanitized HTML). A higher completion cap gives the model
  //    room to FULLY develop every section (substantive article, not an outline)
  //    without truncating mid-draft.
  const draftCompletion = await run(() =>
    args.openai.chat.completions.create({
      model: MODEL,
      max_completion_tokens: 6000,
      messages: buildDraftMessages({ brief, outlineText: outlineToText(outline), opts: { writingInstructions } }),
    }),
  );
  const rawHtml = cleanDraftHtml(completionText(draftCompletion));
  const bodyHtml = sanitizeRawBlogHtml(rawHtml);

  // 3) Metadata (best-effort — an empty metadata set still yields a usable
  //    draft the human/quality-gate can complete).
  let metadata: Partial<BlogMetadata> = {};
  try {
    const metaCompletion = await run(() =>
      args.openai.chat.completions.create({
        model: MODEL,
        max_completion_tokens: 700,
        messages: buildMetadataMessages({
          title: outline.title,
          bodyHtml,
          targetKeyword: brief.targetKeyword,
          fields: METADATA_FIELDS,
          writingInstructions,
        }),
      }),
    );
    metadata = clampMetadata(parseJsonObject(completionText(metaCompletion)));
  } catch {
    metadata = {};
  }

  const title = outline.title;
  const slugBase = metadata.slug?.trim() ? metadata.slug : title;
  const slug = uniqueSlug(slugifyTitle(slugBase), args.existingSlugs);
  const excerpt = metadata.excerpt?.trim() ?? "";

  // Insert the DRAFT (never published) linked to the topic.
  const [row] = await db
    .insert(blogPostsTable)
    .values({
      slug,
      title,
      excerpt,
      body: bodyHtml,
      authorName: "LP Studio",
      tags: normalizeTags(args.topic.targetKeyword ? [args.topic.targetKeyword] : []),
      status: "draft",
      seoTitle: metadata.seoTitle?.trim() || null,
      seoDescription: (metadata.metaDescription ?? metadata.ogDescription)?.trim() || null,
      ogImageUrl: null,
      readingTimeMin: readingTimeMin(bodyHtml),
      topicId: args.topic.id,
    })
    .returning();

  // Link the topic back to the post.
  await db
    .update(blogTopicsTable)
    .set({ postId: row.id })
    .where(eq(blogTopicsTable.id, args.topic.id));

  return { postId: row.id, slug, title, bodyHtml, metadata };
}
