/**
 * User-guide corpus for the in-app support chatbot.
 *
 * Each section is a self-contained "how do I…" topic about LP Studio itself.
 * The bot retrieves sections by keyword match and grounds its answer on the
 * `body` text. Every claim in these bodies was verified against the app
 * source (routes in artifacts/lp-studio/src/App.tsx, the app pages under
 * artifacts/lp-studio/src/pages/*, and the marketing docs pages) — when a
 * feature changes, update the matching section here.
 */

/** One user-guide topic the support bot can ground an answer on. */
export interface GuideSection {
  /** Stable kebab-case id. */
  slug: string;
  /** Human title, e.g. "Publishing and custom domains". */
  title: string;
  /** Lowercase retrieval keywords/synonyms a user might type (8-20 per section). */
  keywords: string[];
  /** Optional in-app route the topic lives at (e.g. "/brand"), when confident. */
  appPath?: string;
  /** The guide content: plain prose + simple hyphen lists, 80-220 words. */
  body: string;
}

export const USER_GUIDE_SECTIONS: GuideSection[] = [
  {
    slug: "what-is-lp-studio",
    title: "What LP Studio is and getting started",
    keywords: [
      "getting started",
      "what is lp studio",
      "overview",
      "intro",
      "onboarding",
      "first steps",
      "dashboard",
      "workspace",
      "landing page builder",
      "sales console",
      "how does it work",
      "begin",
      "new user",
    ],
    appPath: "/",
    body: "LP Studio is one workspace for marketing-built landing pages and sales-built microsites. It combines brand-locked AI page generation, a visual block builder, a template library, per-page analytics, and a Sales Console for account-based selling — with integrations into your CRM and revenue stack. You don't need code or a designer: your brand tokens and approved blocks are set up once, and after that anyone on the team can ship on-brand pages. Most teams publish their first real page within an hour. To get going:\n- Sign in and you land on the Dashboard.\n- Open Brand & Content and import your brand from your website so everything you generate is on-brand.\n- Go to Pages and generate your first page with AI, or start from a template.\n- Publish, then watch visits and leads come in under Analytics.",
  },
  {
    slug: "generate-first-page",
    title: "Generating your first page with AI",
    keywords: [
      "generate page",
      "ai generate",
      "create page",
      "new page",
      "prompt",
      "describe a page",
      "from url",
      "from screenshot",
      "page generation",
      "make a landing page",
      "build a page",
      "blank page",
      "reference url",
    ],
    appPath: "/pages",
    body: "Open Pages and start a new page. In the create dialog, choose AI Generate and describe the page you want in plain language. You can steer the generation a few ways:\n- Pick a template so the AI keeps that block layout, or generate from scratch.\n- Add reference URLs the AI should draw from.\n- Paste or attach a screenshot of a page whose style you like.\nStart the generation and watch the page build live, block by block. When it finishes, the page opens in the builder as a draft where you can edit anything before publishing. Generated copy uses your brand voice and approved facts from Brand & Content, so import your brand first for the best results. If you'd rather start empty, you can also create a blank untitled page and drag blocks in yourself.",
  },
  {
    slug: "builder-basics",
    title: "The builder: editing blocks, undo, and preview",
    keywords: [
      "builder",
      "editor",
      "edit page",
      "blocks",
      "drag and drop",
      "inline editing",
      "properties panel",
      "undo",
      "redo",
      "preview",
      "draft",
      "edit copy",
      "rearrange",
      "review link",
    ],
    body: "Every page opens in the full-screen builder. Pages are made of blocks — hero, features, forms, testimonials, and so on. You can:\n- Drag blocks onto the canvas and reorder them.\n- Click into text to edit copy inline.\n- Select a block to tune its settings, brand, fonts, and colors in the properties panel.\nThe builder keeps a 50-step undo history, so Cmd-Z (Ctrl-Z on Windows) reverts any change, including edits applied by the AI copilot. Use Preview to see the draft exactly as visitors will — the preview link works for anyone signed in to your workspace. To collect feedback from someone without a login, share a review link instead; reviewers open a token-based review page and don't need an account. Nothing is public until you publish.",
  },
  {
    slug: "ask-ai-copilot",
    title: "The Ask AI builder copilot",
    keywords: [
      "ask ai",
      "copilot",
      "ai assistant",
      "ai edits",
      "chatbot",
      "suggestions",
      "apply",
      "rewrite copy",
      "improve page",
      "fix contrast",
      "swap image",
      "ai chat",
      "propose changes",
      "apply all",
    ],
    body: "Inside the builder, click the floating Ask AI button to open the copilot panel — a chat drawer on the right side of the editor. Ask it anything about your page in plain language, or start from one of the suggestion chips, like \"Review my page and propose your top improvements\" or \"Strengthen my hero headline.\" When the copilot wants to change something, it proposes the edit as an action card with a short rationale. It can propose inserting a block, rewriting copy, replacing an image, removing or reordering a block, fixing text contrast, and editing a block's settings. Nothing is applied automatically: you review each card and click Apply or Dismiss, and when a reply includes several proposals you can click Apply all. Applied edits go through the same undo history as manual edits, so Cmd-Z reverts them.",
  },
  {
    slug: "blocks-and-custom-blocks",
    title: "Blocks, block presets, and custom AI-generated blocks",
    keywords: [
      "blocks",
      "block library",
      "block presets",
      "custom blocks",
      "custom html",
      "sections",
      "components",
      "generate block",
      "block types",
      "add section",
      "reusable blocks",
      "html block",
    ],
    appPath: "/blocks",
    body: "Pages are assembled from blocks — reusable sections like heroes, feature grids, forms, and testimonials that all inherit your brand styling. The Blocks page manages your workspace's block setup with two tabs: Block Presets, for the defaults blocks start from, and Custom HTML, for blocks your team defines. On the Custom Blocks page (/custom-blocks) you can create your own blocks in three flavors:\n- Rich text blocks edited in a WYSIWYG editor.\n- Custom HTML blocks for hand-written markup.\n- Schema blocks, where you define fields and a template so editors fill in structured content.\nYou can also generate a custom block with AI instead of writing it by hand. Each custom block shows where it's used, including how many published pages depend on it, so you can edit safely.",
  },
  {
    slug: "brand-settings-and-import",
    title: "Brand settings and importing your brand from a URL",
    keywords: [
      "brand",
      "brand settings",
      "import brand",
      "import from url",
      "import from website",
      "brand guidelines",
      "colors",
      "fonts",
      "typography",
      "logo",
      "voice",
      "brand kit",
      "on-brand",
      "approved facts",
      "strict ai facts",
    ],
    appPath: "/brand",
    body: "Open Brand & Content to control how everything you ship looks and sounds. The fastest setup is Import from Website: paste your site's URL and LP Studio scrapes your homepage and sub-pages, extracting logos, colors, typography, voice, and imagery, then proposes every brand token for you to review and apply. There's also Import from Guidelines if you have a brand guidelines document. After import you can fine-tune each section by hand: Logo, Colors, Typography, Buttons & UI Elements, Voice & Messaging, section spacing, and the default social share card. The page also holds your approved-facts library — claims and stats your AI copy can quote. With Strict AI facts mode on, generated copy only quotes facts you've explicitly checked as approved, which keeps AI pages accurate. Everything generated afterward is on-brand by default.",
  },
  {
    slug: "images-and-media-library",
    title: "Images, videos, and the media library",
    keywords: [
      "images",
      "media library",
      "upload image",
      "photos",
      "pictures",
      "video",
      "assets",
      "replace image",
      "generate image",
      "ai image",
      "image picker",
      "swap image",
      "tags",
    ],
    body: "Your workspace has a shared media library for images, videos, and documents. Open it from any image control in the builder or Brand & Content: it slides out as a drawer where you can upload files, search, and organize assets with tags. Images harvested when you ran a brand import from your website land in the library too, so your real product photography is ready to use. To change an image on a page, select the block and use its image picker to choose from the library or upload something new. Where AI image generation is enabled for your workspace, the image picker also offers a Generate button that creates an on-brand image from a short brief. The Ask AI copilot can propose image swaps as well — you review and apply them like any other suggestion.",
  },
  {
    slug: "forms-leads-and-notifications",
    title: "Forms, leads, and lead notifications",
    keywords: [
      "forms",
      "leads",
      "submissions",
      "lead capture",
      "form builder",
      "email notification",
      "notify",
      "recipients",
      "follow-up email",
      "thank you page",
      "form settings",
      "new lead alert",
      "contact form",
    ],
    appPath: "/forms-and-leads",
    body: "Forms & Leads is the home for lead capture, with three tabs: Forms, Submissions, and Integrations. Each form has its own settings, including a Notifications tab where you add email recipients who get an email for every new submission — add as many addresses as you need. Forms can also send a follow-up email to the person who submitted, using an email template you pick. After submitting, visitors land on a thank-you page. All submissions collect in the Submissions tab, and each form can additionally push its leads out via the Integrations tab — to your CRM, a Google Sheet, Slack, or any webhook URL. Workspace-level alert recipients (who gets collaboration and account emails) are managed separately under Settings, in the Email tab's Alert recipients section.",
  },
  {
    slug: "lead-capture-chat-block",
    title: "The Lead Capture Chat block (page chatbot)",
    keywords: [
      "chat",
      "chatbot",
      "chat bot",
      "lead capture chat",
      "chat widget",
      "chat bubble",
      "live chat",
      "conversational",
      "page assistant",
      "visitor questions",
      "capture leads",
      "talk to visitors",
      "ai chat on page",
    ],
    body: "The Lead Capture Chat block adds an AI chat bubble to a published landing page. Visitors can ask questions and the bot answers strictly from that page's own content and your approved brand facts — it never invents pricing, guarantees, or claims, and says so when it doesn't know. When a visitor shares their email (the bot works toward this naturally), the conversation is captured as a lead through the same pipeline as your forms, so notifications, CRM syncs, and attribution all apply. To use it: in the builder, add the \"Lead Capture Chat\" block from the Lead Capture category, then configure it in the properties panel — bot name, welcome message, which contact fields to collect (name, company, phone), qualifying questions it should weave in, an optional linked form (so that form's notification and integration routing applies), consent small-print, launcher position and color, and an optional auto-open delay. The bubble only goes live on the published page; in the builder you see a preview card. It answers only from page content, so make sure the page itself covers what visitors usually ask.",
  },
  {
    slug: "integrations",
    title: "Integrations: CRM, Slack, Sheets, Zapier, and webhooks",
    keywords: [
      "integrations",
      "salesforce",
      "marketo",
      "hubspot",
      "slack",
      "google sheets",
      "zapier",
      "webhook",
      "chili piper",
      "crm sync",
      "ga4",
      "google analytics",
      "connect",
      "rb2b",
      "apollo",
      "lead sync",
    ],
    appPath: "/integrations",
    body: "LP Studio ships native integrations across the revenue stack:\n- Salesforce: two-way sync with per-tenant field mapping; form fills create Leads or Opportunities, and the Sales Console pulls pipeline context back in.\n- Marketo: two-way lead sync using your REST endpoint plus LaunchPoint client credentials, de-duplicated by lead ID.\n- HubSpot: pushes leads as contacts via a private-app access token.\n- Google Sheets: appends each submission as a row in a sheet you pick.\n- Slack: posts new submissions to a channel via an incoming webhook URL.\n- Chili Piper: opens the scheduler inline so qualified leads book a meeting on submit.\n- Google Analytics 4: add your Measurement ID and pages report views and conversions.\n- RB2B and Apollo: visitor identification and signals via your site keys.\nEvery form also supports outbound webhooks — LP Studio POSTs the field values, page slug and title, timestamp, and UTM parameters as JSON to any URL. That's how Zapier connects too: use a Webhooks by Zapier Catch Hook as the form's webhook.",
  },
  {
    slug: "publishing-and-custom-domains",
    title: "Publishing, page URLs, and custom domains",
    keywords: [
      "publish",
      "go live",
      "custom domain",
      "domain",
      "dns",
      "cname",
      "ssl",
      "url",
      "subdomain",
      "unpublish",
      "hosting",
      "page address",
      "live page",
    ],
    appPath: "/settings/domain",
    body: "Publish a page from the builder — you'll confirm, and the page becomes publicly accessible. Pages are hosted for you on fast, globally cached infrastructure with SSL handled automatically. Every workspace gets a managed LP Studio web address that's always live with no DNS setup; you can edit its label under Settings, in the Domain tab. To serve pages from your own domain, a workspace admin opens Settings → Domain, attaches the custom domain, and adds the CNAME record LP Studio shows at your DNS provider. The page polls the status and flips to active once DNS propagates, with SSL issued automatically. Custom domains are available on paid plans. Published page URLs use the page's slug — on the managed address they live under /lp/your-slug, and on a custom or microsite domain directly under /your-slug.",
  },
  {
    slug: "seo-and-social-share",
    title: "SEO, indexing, and social share cards",
    keywords: [
      "seo",
      "meta",
      "search engine",
      "google indexing",
      "noindex",
      "og image",
      "open graph",
      "share card",
      "social preview",
      "link preview",
      "meta description",
      "discoverability",
    ],
    appPath: "/settings/seo",
    body: "Settings → SEO controls whether search engines and AI crawlers can index your published pages. When indexing is on, pages can appear in Google, Bing, and AI search results; when off, pages carry a noindex directive — useful when your pages are private 1:1 prospect pages. That's the workspace default, and individual pages can override it from the page's own Settings tab in the builder. For how links look when shared, set a default share card in Brand & Content: title, description, and image, with a page-title placeholder so each page fills in its own name. Pages can customize their share card too, with a live preview and character-count guidance in the builder. Published pages are statically rendered and served from a globally cached host, so they load fast — which helps both SEO and paid-traffic quality scores.",
  },
  {
    slug: "ab-testing-and-smart-traffic",
    title: "A/B testing and Smart Traffic",
    keywords: [
      "ab test",
      "a/b testing",
      "split test",
      "variants",
      "experiment",
      "smart traffic",
      "winning variant",
      "conversion test",
      "traffic split",
      "significance",
      "test results",
      "optimize",
    ],
    appPath: "/tests",
    body: "Create A/B tests from the Tests area, or spin a test up directly from an existing page in the Pages gallery. A test holds multiple variants of a page; visitors are split between them and each variant's performance is tracked. You set the metric that decides the winner — things like clicks, signups, or booked meetings — and LP Studio detects statistical significance automatically. On the test's detail page you control how traffic is divided:\n- Manual weights: you set each variant's share of traffic.\n- Smart Traffic: LP Studio routes the majority of visitors to the winning variant once it's clear, after a minimum sample size you can configure.\nOpen a test to see per-variant performance side by side and adjust or end the test when you have your answer.",
  },
  {
    slug: "analytics-visits-and-heatmaps",
    title: "Analytics, visits, and heatmaps",
    keywords: [
      "analytics",
      "visits",
      "traffic",
      "conversions",
      "heatmap",
      "click map",
      "scroll depth",
      "stats",
      "reporting",
      "visitors",
      "page performance",
      "who visited",
      "identity",
      "metrics",
    ],
    appPath: "/analytics",
    body: "The Analytics area covers every published page, with views for an overview, per-page numbers, visitor locations, and conversions. Open a specific page's analytics to see visits, leads, conversion rate, average scroll depth, and CTA clicks, plus traffic sources and a visits table. The table shows known and anonymous visitors together: links sent through the Sales Console carry deterministic per-recipient identity, so a visit row can say exactly which contact viewed the page and what they did, not just which company. Further down the page detail you'll find a heatmap of click and scroll behavior across the page, so you can see what people actually engage with. You can also forward events to Google Analytics 4 and your CRM via integrations, so the same data shows up where your revenue team already looks.",
  },
  {
    slug: "sales-console",
    title: "Sales Console: accounts, microsites, one-pagers, and signals",
    keywords: [
      "sales console",
      "accounts",
      "microsites",
      "one-pager",
      "signals",
      "outreach",
      "abm",
      "contacts",
      "draft email",
      "hot accounts",
      "sales pages",
      "roi calculator",
      "campaigns",
      "rep",
    ],
    appPath: "/sales",
    body: "The Sales Console is an ABM command center for reps, on plans that include it. The dashboard surfaces hot accounts and live visitor signals, with a one-click AI brief per account. From there:\n- Accounts and Contacts track your book of business with per-contact engagement.\n- Microsites are per-account pages reps spin up for their deals, served from your microsite domain.\n- Campaigns and the AI draft-email tool generate personalized outreach that carries tokenized links, so you know exactly who clicked and what they read.\n- Signals is the feed of visitor and engagement events across your pages.\n- One-pagers generate brand-styled PDF leave-behinds from templates, with an editor and template gallery.\n- An ROI calculator helps build the business case for a deal.\nCRM connections for the console (Salesforce, Marketo, HubSpot, Slack) are configured from the console's own integrations settings.",
  },
  {
    slug: "templates",
    title: "Templates and starting from an existing page",
    keywords: [
      "templates",
      "template library",
      "marketplace",
      "clone",
      "duplicate page",
      "starter",
      "industry templates",
      "use template",
      "copy page",
      "save as template",
      "examples",
      "gallery",
    ],
    appPath: "/templates",
    body: "The Templates page is a marketplace of 100+ on-brand templates shown as live previews, filterable by industry and page type, so you never start from a blank page. There are two ways to use one:\n- Use Template clones it verbatim into your Pages, inheriting your brand tokens, so it immediately looks like you.\n- Generate from a template keeps its block layout but has AI rewrite the copy and imagery for your brief — pick the template inside the AI Generate dialog when creating a page.\nYou can also save one of your own pages as a template so teammates can reuse a layout that works, and clone any existing page as the starting point for a new one from the Pages gallery.",
  },
  {
    slug: "plans-and-billing",
    title: "Plans, trials, and billing",
    keywords: [
      "plans",
      "billing",
      "pricing",
      "upgrade",
      "downgrade",
      "subscription",
      "free tier",
      "trial",
      "cancel",
      "payment",
      "invoice",
      "plan limits",
      "renewal",
      "seats",
    ],
    appPath: "/settings/billing",
    body: "Plans are capability-based tiers:\n- Free is forever: a single page and form with a \"Powered by LP Studio\" badge — enough to kick the tires.\n- Starter removes the badge, unlocks more pages, and adds your own custom domain.\n- Growth adds the Sales Console — microsites, AI outreach, signals, and CRM sync.\n- Scale is for multi-brand, multi-team operations with higher limits.\n- Enterprise is sales-assisted, adding SSO, SLA, and a dedicated CSM.\nEvery paid tier starts with a 14-day Growth trial, no credit card required. Any workspace member can open Settings → Billing to see the current plan and renewal date; upgrading and managing billing are admin-only actions on the same page. Month-to-month plans cancel right from Billing — no calls or contract clauses — and annual plans pause at renewal. For current prices, check the Billing page or the public pricing page.",
  },
  {
    slug: "troubleshooting-common-questions",
    title: "Troubleshooting and common questions",
    keywords: [
      "troubleshooting",
      "faq",
      "not working",
      "problem",
      "page not showing",
      "not receiving leads",
      "not in google",
      "common questions",
      "help",
      "issue",
      "error",
      "questions",
    ],
    body: "Quick answers to the most common questions:\n- How fast can I launch? Most teams ship their first real page within an hour — generate with AI or start from a template, then publish.\n- Do I need a designer or engineer? No. Brand tokens and approved blocks are set up once; after that anyone can ship on-brand pages. Devs can optionally extend the block library.\n- Where do pages live? On fast, globally cached hosting with SSL handled, or on your own domain via a CNAME record.\n- My page isn't showing in Google: check Settings → SEO — the workspace indexing toggle may be off (noindex), and individual pages can override it in their Settings tab.\n- I'm not getting lead emails: open the form in Forms & Leads and check the Notifications tab — your address must be listed as a recipient.\n- A change looks wrong: the builder has 50 steps of undo (Cmd-Z), including AI-applied edits.",
  },
  {
    slug: "getting-more-help",
    title: "Getting more help",
    keywords: [
      "support",
      "contact",
      "help",
      "email support",
      "reach out",
      "feature request",
      "integration request",
      "talk to sales",
      "feedback",
      "human",
      "customer support",
      "bug report",
    ],
    body: "The fastest way to get help is this assistant: click the ? bubble in the bottom-right of any app page and ask in plain language — it answers from this guide and can take you straight to the right page. If it can't resolve your question, it offers to hand off to the LP Studio team, or you can email admin@lpstudio.ai directly — the same address handles product questions, integration requests, and privacy or account-data requests. For plan and billing questions, start at Settings → Billing, where any workspace member can see the current plan and renewal date and admins can manage the subscription; that page also has a talk-to-sales link for Enterprise conversations. If you spot something wrong on a specific page, remember the fastest fixes are often in-app: the Ask AI copilot in the builder can review your page and propose improvements, and the builder's undo history reverts any recent change.",
  },
];
