// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/brand-palettes/Coral.tsx": () => import("../components/mockups/brand-palettes/Coral.tsx"),
  "./components/mockups/brand-palettes/Indigo.tsx": () => import("../components/mockups/brand-palettes/Indigo.tsx"),
  "./components/mockups/brand-palettes/Studio.tsx": () => import("../components/mockups/brand-palettes/Studio.tsx"),
  "./components/mockups/business-case/Centered.tsx": () => import("../components/mockups/business-case/Centered.tsx"),
  "./components/mockups/business-case/Split.tsx": () => import("../components/mockups/business-case/Split.tsx"),
  "./components/mockups/premium-abm-microsite/Page.tsx": () => import("../components/mockups/premium-abm-microsite/Page.tsx"),
  "./components/mockups/premium-annual-report/Page.tsx": () => import("../components/mockups/premium-annual-report/Page.tsx"),
  "./components/mockups/premium-documentary-story/Page.tsx": () => import("../components/mockups/premium-documentary-story/Page.tsx"),
  "./components/mockups/premium-keynote/AppleDark.tsx": () => import("../components/mockups/premium-keynote/AppleDark.tsx"),
  "./components/mockups/premium-keynote/AppleLight.tsx": () => import("../components/mockups/premium-keynote/AppleLight.tsx"),
  "./components/mockups/premium-keynote/BaseDark.tsx": () => import("../components/mockups/premium-keynote/BaseDark.tsx"),
  "./components/mockups/premium-keynote/BaseLight.tsx": () => import("../components/mockups/premium-keynote/BaseLight.tsx"),
  "./components/mockups/premium-keynote/LinearDark.tsx": () => import("../components/mockups/premium-keynote/LinearDark.tsx"),
  "./components/mockups/premium-keynote/LinearLight.tsx": () => import("../components/mockups/premium-keynote/LinearLight.tsx"),
  "./components/mockups/premium-story-hub-cream/Dark.tsx": () => import("../components/mockups/premium-story-hub-cream/Dark.tsx"),
  "./components/mockups/premium-story-hub-cream/Light.tsx": () => import("../components/mockups/premium-story-hub-cream/Light.tsx"),
  "./components/mockups/premium-story-hub-dark/Dark.tsx": () => import("../components/mockups/premium-story-hub-dark/Dark.tsx"),
  "./components/mockups/premium-story-hub-dark/Light.tsx": () => import("../components/mockups/premium-story-hub-dark/Light.tsx"),
  "./components/mockups/premium-story-hub-magazine/Dark.tsx": () => import("../components/mockups/premium-story-hub-magazine/Dark.tsx"),
  "./components/mockups/premium-story-hub-magazine/Light.tsx": () => import("../components/mockups/premium-story-hub-magazine/Light.tsx"),
  "./components/mockups/spatial-tour-dynamic-nav/Variant.tsx": () => import("../components/mockups/spatial-tour-dynamic-nav/Variant.tsx"),
  "./components/mockups/spatial-tour-live-telemetry/Variant.tsx": () => import("../components/mockups/spatial-tour-live-telemetry/Variant.tsx"),
  "./components/mockups/spatial-tour-video-hero/Variant.tsx": () => import("../components/mockups/spatial-tour-video-hero/Variant.tsx")
};
