// This file is auto-generated by mockupPreviewPlugin.ts.
//
// To register custom mockup components:
// 1. Create your component in src/components/mockups/ directory
// 2. Export it as default or named export (Preview, ComponentName, etc.)
// 3. The mockupPreviewPlugin will automatically discover and register it here
//
// Example component structure:
// src/components/mockups/ExampleComponent.tsx
// export default function ExampleComponent() {
//   return <div>Your component here</div>;
// }
//
// Then access the preview at: /preview/ExampleComponent

type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  // Custom components will be auto-registered here by mockupPreviewPlugin
};
