// Task #1138 — client API for the Strict Facts review flow. Replaces the old
// ephemeral sessionStorage hand-off (strictMismatches.ts) with persistent,
// per-page fact flags served by the api-server. All mutating calls go through
// the global window.fetch CSRF interceptor automatically.
const API_BASE = "/api";

export type FactKind = "stat" | "claim" | "quote";
export type TriageState =
  | "pending"
  | "approved_for_page"
  | "edited"
  | "swapped"
  | "removed";

export interface FactFlag {
  id: number;
  pageId: number;
  factKind: FactKind;
  normalizedForm: string;
  blockId: string | null;
  blockType: string | null;
  fieldPath: string;
  originalText: string;
  triageState: TriageState;
  replacementText: string | null;
  swappedWithProofPointId: number | null;
  librarySaved: boolean;
  source: string;
  attributionName: string | null;
  attributionTitle: string | null;
  attributionCompany: string | null;
  contextLabel: string | null;
  resolvedAt: string | null;
}

export interface FactFlagList {
  flags: FactFlag[];
  pendingCount: number;
  total: number;
}

export interface ProofPointOption {
  id: number;
  value: string;
  label: string;
  attributionName: string | null;
}

async function post<T>(url: string, body?: unknown): Promise<T> {
  const res = await fetch(`${API_BASE}${url}`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(body ?? {}),
  });
  if (!res.ok) throw new Error((await res.json().catch(() => ({}))).error ?? "Request failed");
  return res.json() as Promise<T>;
}

export async function listFactFlags(pageId: number | string): Promise<FactFlagList> {
  const res = await fetch(`${API_BASE}/lp/pages/${pageId}/fact-flags`);
  if (!res.ok) return { flags: [], pendingCount: 0, total: 0 };
  return res.json() as Promise<FactFlagList>;
}

/** Detect + persist pending flags for a saved page (regen-memory aware). Call
 *  this right after a page is created/regenerated by AI. */
export async function syncFactFlags(
  pageId: number | string,
  templateForms?: string[],
): Promise<FactFlagList & { created: number; mutated: boolean }> {
  return post(`/lp/pages/${pageId}/fact-flags/sync`, { templateForms: templateForms ?? [] });
}

export async function approveFactFlag(id: number): Promise<{ flag: FactFlag }> {
  return post(`/lp/fact-flags/${id}/approve`);
}
export async function editFactFlag(id: number, replacementText: string): Promise<{ flag: FactFlag }> {
  return post(`/lp/fact-flags/${id}/edit`, { replacementText });
}
export async function swapFactFlag(id: number, proofPointId: number): Promise<{ flag: FactFlag }> {
  return post(`/lp/fact-flags/${id}/swap`, { proofPointId });
}
export async function removeFactFlag(id: number): Promise<{ flag: FactFlag }> {
  return post(`/lp/fact-flags/${id}/remove`);
}
export async function saveFactToLibrary(
  id: number,
  opts?: { value?: string; label?: string },
): Promise<{ flag: FactFlag; proofPointId?: number }> {
  return post(`/lp/fact-flags/${id}/save-to-library`, opts ?? {});
}
export async function undoFactFlag(id: number): Promise<{ flag: FactFlag }> {
  return post(`/lp/fact-flags/${id}/undo`);
}
export async function bulkApproveFactFlags(
  pageId: number | string,
  flagIds?: number[],
): Promise<{ approved: number; flags: FactFlag[] }> {
  // Omit the body field entirely for the approve-all case so the server keeps
  // its "no flagIds → all pending" default; pass the subset only when selecting.
  return post(
    `/lp/pages/${pageId}/fact-flags/bulk-approve`,
    flagIds === undefined ? undefined : { flagIds },
  );
}
export async function getProofPointsForKind(factKind: FactKind): Promise<ProofPointOption[]> {
  const res = await fetch(`${API_BASE}/lp/fact-flags/proof-points?factKind=${encodeURIComponent(factKind)}`);
  if (!res.ok) return [];
  return res.json() as Promise<ProofPointOption[]>;
}
