import { Router } from "express";
import testsRouter from "./tests";
import variantsRouter from "./variants";
import trackingRouter from "./tracking";
import resultsRouter from "./results";
import brandRouter from "./brand";
import pagesRouter from "./pages";
import collaborationRouter from "./collaboration";
import analyticsRouter from "./analytics";
import libraryRouter from "./library";
import blockDefaultsRouter from "./block-defaults";
import customBlocksRouter from "./custom-blocks";
import brandPresetsRouter from "./brand-presets";
import brandImportRouter from "./brand-import";
import copyGenerateRouter from "./copy-generate";
import leadsRouter from "./leads";
import formNotificationsRouter from "./form-notifications";
import formsRouter from "./forms";
import generatePageRouter from "./generate-page";
import seoAnalyzeRouter from "./seo-analyze";
import seoMetaGenerateRouter from "./seo-meta-generate";
import integrationsRouter from "./integrations";
import smartTrafficRouter from "./smart-traffic";
import heatmapRouter from "./heatmap";
import performanceRouter from "./performance";
import personalizedLinksRouter from "./personalized-links";
import tokenResolveRouter from "./token-resolve";
import contentBriefRouter from "./content-brief";
import inUseImagesRouter from "./in-use-images";
import templatesRouter from "./templates";
import conversionScoringRouter from "./conversion-scoring";
import pageSpeedRouter from "./page-speed";
import ampPagesRouter from "./amp-pages";
import programmaticPagesRouter from "./programmatic-pages";
import adMapRouter from "./ad-map";

const router = Router();

router.use(testsRouter);
router.use(variantsRouter);
router.use(trackingRouter);
router.use(resultsRouter);
router.use(brandRouter);
router.use(performanceRouter); // Must come before pagesRouter to avoid /lp/pages/:pageId catching /lp/pages/performance/batch
router.use(pagesRouter);
router.use(collaborationRouter);
router.use(analyticsRouter);
router.use(libraryRouter);
router.use(blockDefaultsRouter);
router.use(customBlocksRouter);
router.use(brandPresetsRouter);
router.use(brandImportRouter);
router.use(copyGenerateRouter);
router.use(leadsRouter);
router.use(formNotificationsRouter);
router.use(formsRouter);
router.use(generatePageRouter);
router.use(seoAnalyzeRouter);
router.use(seoMetaGenerateRouter);
router.use(integrationsRouter);
router.use(smartTrafficRouter);
router.use(heatmapRouter);
router.use(pageSpeedRouter); // Page Speed Engine routes
router.use(personalizedLinksRouter);
router.use(tokenResolveRouter);
router.use(contentBriefRouter);
router.use(inUseImagesRouter);
router.use(templatesRouter);
router.use(conversionScoringRouter);
router.use(ampPagesRouter);
router.use(programmaticPagesRouter);
router.use(adMapRouter);

export default router;
